name: documentation

on: [workflow_dispatch]

permissions:
  contents: write
env:
  UV_SYSTEM_PYTHON: 1
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.13"
      - name: Install the docs dependencies
        run: uv sync --locked --only-group docs
      - name: Sphinx build
        run: |
          cd docs/ && uv run sphinx-build source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/